# Site settings
title: Code & Chill
description: Code & Chill

# User settings
username: Recep Çil
user_description: I have graduated with a bachelor’s degree in Computer Engineering as top-scoring student from Duzce University and I am currently working as a software development expert at VeriPark to provide specific solutions to clients which include the world’s largest and most respected banking, insurance and finance companies.
user_title: I am a full-stack software developer.
email: r.cilrecep@gmail.com
linkedIn_username: https://www.linkedin.com/in/recepcil/
github_username:  https://github.com/RecepCil

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']